version: '3'

services:
  mysql:
    image: mysql:5.7
    restart: always
    container_name: mysql
    ports:
      - '3306:3306'
    volumes:
      - './mysql:/var/lib/mysql'
    environment:
      MYSQL_ROOT_PASSWORD: yunilugi

  nginx:
    image: nginx:1.13.5
    restart: always
    container_name: nginx
    ports:
      - '80:80'
    volumes:
      - './nginx/html:/usr/share/nginx/html'
      - './nginx/etc:/etc/nginx'